# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main, future ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        
    - name: Grant execute permission for decrypt
      run: chmod +x ./app/decrypt.sh
      
    - name: Decrypt secret
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_FB_PASSPHRASE }}
      run: ./app/decrypt.sh
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test application
      run: ./gradlew test
      
    - name: Build APK
      run: ./gradlew assembleRelease
      
    - name: Change working directory
      run: cd "app/build/outputs/apk/release/"
      
    - name: Create keytool
      run:  keytool -genkey -v -keystore stager-release-key.jks -keyalg RSA -keysize 2048 -validity 10000 -alias stager-key
    
    - name: Shrink APK
      run: zipalign -v -p 4 app-release-unsigned.apk stager-aligned.apk
    
    - name: Sign APK
      run: apksigner sign --ks stager-release-key.jks --out app-release-unsigned.apk stager-aligned.apk
    
    - name: Rename signed APK
      run: mv ./app-release-unsigned.apk ./stager.apk
    
    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: stager.apk
        path: ./stager.apk
