# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main, future ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for decrypt
      run: chmod +x ./app/decrypt.sh
    - name: Decrypt secret
      run: ./app/decrypt.sh
      env:
        SECRET_PASSPHRASE: ${{ secrets.SECRET_FB_PASSPHRASE }}
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Test application
      run: ./gradlew test
    - name: Build APK
      run: ./gradlew assembleRelease
    - name: Upload APK (Unsigned)
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release-unsigned.apk
